package com.opennxt.net

import com.opennxt.net.login.LoginType
import io.netty.util.AttributeKey

object RSChannelAttributes {
    // An id generated by the server that the client sends in the RSA-encrypted login block. Prevents packet replaying
    //  attacks.
    val LOGIN_UNIQUE_ID = AttributeKey.newInstance<Long>("login-unique-id")

    val LOGIN_TYPE = AttributeKey.newInstance<LoginType>("login-type")
}